/* Contenido editorial y traducciones de Temporada (es, en, fr, pt).
 *
 * Todo lo que aquí se afirma es información general verificable (aeropuertos,
 * temporada oficial de huracanes, rutas del Tren Maya) o consejo editorial
 * marcado como tal. Las cifras de gente vienen del pronóstico, no de aquí.
 * Fotos: web/viaja/img/creditos.json (Wikimedia Commons).
 */
window.TEMPORADA_CONTENIDO = {
  idiomas: { es: "Español", en: "English", fr: "Français", pt: "Português" },

  // Fondo de la portada por destino. Tomas: fotos (Ken Burns). Para usar un video propio
  // (p. ej. generado con Higgsfield), copia el .mp4 a web/viaja/img/ y pon su nombre en `video`.
  fondos: {
    cancun: { tomas: ["postal_cancun", "cancun", "el_rey"], video: "fondo_cancun.mp4" },
    riviera_maya: { tomas: ["postal_tulum", "tulum", "postal_playa", "dos_ojos"], video: "fondo_riviera.mp4" },
    gran_costa_maya: { tomas: ["postal_bacalar", "canal_piratas", "bacalar_manana", "mahahual_barcas"], video: "fondo_gcm.mp4" },
  },

  // ------------------------------------------------------------------ interfaz
  ui: {
    es: {
      saltar: "Ir al buscador",
      nav_como: "Cómo estará", nav_cuando: "Cuándo ir", nav_hacer: "Qué hacer", nav_comer: "Comida", nav_faq: "Preguntas",
      vuelos_barra: "Buscar vuelos",
      antetitulo: "Quintana Roo · Cancún · Riviera Maya · Bacalar",
      titular: "Llega cuando el mar <em>es tuyo.</em>",
      bajada: "Dinos a dónde y cuándo quieres ir. Te mostramos cuánta gente habrá, qué pasa esas fechas y qué hacer.",
      frase_ir: "Quiero ir a", frase_el: "el", placeholder: "15 de enero", ver: "Ver cómo estará",
      prueba: "Prueba:", sugerencias: ["Semana Santa", "Verano", "Navidad", "Octubre"],
      cal_titulo: "¿Qué mes?", cal_ayuda: "Las olitas muestran cuánta gente suele haber.",
      cal_festivo: "Día festivo", cal_vacaciones: "Vacaciones en México", cal_finde: "Fin de semana", cal_cerrar: "Cerrar calendario",
      abrir_cal: "Elegir en el calendario", fecha_label: "Fecha del viaje",
      pista_mes: "o elige el día en el calendario",
      err_fecha: "No entendimos esa fecha. Prueba con «15 de enero», «marzo» o «Semana Santa».",
      err_pasada: "Esa fecha ya pasó. Elige una próxima.",
      err_rango: "Por ahora puedes planear hasta diciembre de 2027.",
      err_vacia: "Escribe una fecha, por ejemplo «15 de enero».",
      playa_caption: "Así se sentiría la playa ese día",
      playa_ayuda: "Pasa el dedo o el cursor para comparar",
      playa_ventanas: "Ventanas encendidas = cuartos de hotel ocupados",
      estara: "{d} estará",
      vuelos_a: "Vuelos a {c} · {f}",
      cambiar_fecha: "Cambiar fecha",
      moverte: "¿Puedes moverte un mes?",
      alt_eyebrow: "Mismo Caribe, menos gente",
      alt_titulo: "¿Y si mejor vas a <em>{d}?</em>",
      alt_boton: "Ver {d} el {f}",
      nivel_el: "{n} el {f}",
      cuando_eyebrow: "Cuándo ir",
      cuando_titulo: "El año, <em>ola por ola.</em>",
      cuando_nota: "Entre más alta y más roja la ola, más gente. Toca un mes para ver cómo estará.",
      mejores: "Las fechas más tranquilas para {d}",
      planear_mes: "Planear {m} →",
      dia_eyebrow: "Tu día ideal",
      dia_titulo: "Cada lugar tiene <em>su hora.</em>",
      manana: "Mañana", tarde: "Tarde", noche: "Noche",
      ve_de: "Ve de {m}",
      lugares_eyebrow: "Qué hacer",
      lugares_titulo: "Imperdibles de <em>{d}</em>",
      posible_sargazo: "Posible sargazo",
      tipos: { cultura: "Cultura maya", naturaleza: "Naturaleza", mar: "Mar", playa: "Playa", cenote: "Cenote", comida: "Para cenar" },
      postales_eyebrow: "Postales",
      postales_titulo: "Así se ve <em>Quintana Roo.</em>",
      comida_eyebrow: "Qué probar",
      comida_titulo: "La península <em>se come.</em>",
      comida_consejos: "Consejos para comer bien",
      donde_comer: "Dónde comer en {d}",
      osm_nota: "Lista de OpenStreetMap con prioridad a la cocina regional. Toca «Ver reseñas» para ver su calificación en Google Maps.",
      moverse_eyebrow: "Cómo moverte",
      moverse_titulo: "Del norte al sur, <em>sin prisa.</em>",
      faq_eyebrow: "Preguntas frecuentes",
      faq_titulo: "Lo que todos <em>preguntan.</em>",
      destinos_eyebrow: "Tres destinos",
      destinos_titulo: "Un estado, <em>tres ritmos.</em>",
      region_de: "{r} de Quintana Roo",
      con_calma: "Para ir con calma: {m}.",
      planear_aqui: "Planear aquí",
      pie_grande: "Quédate <em>la noche.</em>",
      pie_nota: "Las predicciones son estimaciones hechas con datos oficiales de turismo de Quintana Roo.",
      creditos: "Créditos",
      osm_credito: "Restaurantes: © colaboradores de OpenStreetMap (ODbL)",
      autoridades: "Para autoridades: sistema CAUCE ↗",
      sin_conexion_t: "Sin conexión", sin_conexion_x: "No pudimos cargar el pronóstico.",
      idioma: "Idioma",
      ev_mas_t: "De las fechas con más gente del año", ev_mas_x: "{m} es de los meses favoritos para ir a {d}.",
      ev_menos_t: "De las fechas más tranquilas del año", ev_menos_x: "Pocos viajeros eligen {m}: tendrás más espacio para ti.",
      ev_vac_x: "Esa semana viajan muchas familias mexicanas: sube la gente aunque el mes sea tranquilo. Reserva con tiempo.",
      ev_puente_t: "Fin de semana largo", ev_puente_x: "{f}: viajan más familias mexicanas.",
      ev_festivo_x: "Hay un día festivo cerca de tu fecha.",
      ev_finde_t: "Cae en fin de semana", ev_finde_x: "Entre semana los lugares famosos tienen más espacio.",
      ev_sarg_alto_t: "Temporada de sargazo", ev_sarg_alto_x: "Puede llegar alga a las playas. La laguna de Bacalar y los cenotes siguen perfectos.",
      ev_sarg_medio_t: "Puede haber sargazo", ev_sarg_medio_x: "Algunas playas podrían tener alga esos días.",
      ev_visit_t: "Llegan unos {n} mil visitantes", ev_visit_x: "a {d} durante {m}.",
      argumento: {
        gran_costa_maya: "La laguna de Bacalar, cenotes y zonas mayas en la selva, con una fracción de la gente. Aquí te quedas la noche.",
        riviera_maya: "Ruinas frente al mar, cenotes y la reserva de Sian Ka'an, con menos gente ese mes.",
        cancun: "Playas abiertas al Caribe, la zona arqueológica El Rey y más cuartos libres ese mes.",
      },
      mov_bus: "Llega en autobús", mov_tren: "…o en Tren Maya", mov_avion: "…o vuela directo", mov_bienvenida: "Bienvenido a Quintana Roo",
      dormir_eyebrow: "Dónde dormir", dormir_titulo: "Quédate <em>la noche.</em>", todas: "Todas", ver_resenas: "Ver reseñas en Google Maps", resenas_nota: "Las calificaciones y reseñas se consultan directo en Google Maps: ahí verás las estrellas (de 1 a 5) y cuántas personas opinaron. Un 4.5 con cientos de reseñas dice más que un 5 con tres. Lista de OpenStreetMap; no es un ranking.", tipo_hotel: "Hotel", tipo_hostel: "Hostal", tipo_guest_house: "Casa de huéspedes", estrellas_cat: "{n} estrellas (categoría)", sitio_web: "Sitio web",
      bot_titulo: "Pregúntale a Temporada", bot_sub: "Respuestas sobre Quintana Roo, al instante",
      bot_placeholder: "Escribe tu pregunta…", bot_enviar: "Enviar", bot_abrir: "Abrir asistente", bot_cerrar: "Cerrar asistente",
    },
    en: {
      saltar: "Skip to search",
      nav_como: "What to expect", nav_cuando: "When to go", nav_hacer: "Things to do", nav_comer: "Food", nav_faq: "FAQ",
      vuelos_barra: "Find flights",
      antetitulo: "Quintana Roo · Cancún · Riviera Maya · Bacalar",
      titular: "Arrive when the sea <em>is yours.</em>",
      bajada: "Tell us where and when you want to go. We'll show you how crowded it will be, what's happening those days and what to do.",
      frase_ir: "I want to go to", frase_el: "on", placeholder: "January 15", ver: "See what it's like",
      prueba: "Try:", sugerencias: ["Holy Week", "Summer", "Christmas", "October"],
      cal_titulo: "Which month?", cal_ayuda: "The little waves show how busy it usually gets.",
      cal_festivo: "Public holiday", cal_vacaciones: "Mexican school holidays", cal_finde: "Weekend", cal_cerrar: "Close calendar",
      abrir_cal: "Pick on the calendar", fecha_label: "Travel date",
      pista_mes: "or pick the exact day on the calendar",
      err_fecha: "We didn't get that date. Try “January 15”, “March” or “Holy Week”.",
      err_pasada: "That date has passed. Pick an upcoming one.",
      err_rango: "For now you can plan up to December 2027.",
      err_vacia: "Type a date, for example “January 15”.",
      playa_caption: "How the beach would feel that day",
      playa_ayuda: "Hover or tap to compare",
      playa_ventanas: "Lit windows = occupied hotel rooms",
      estara: "{d} will be",
      vuelos_a: "Flights to {c} · {f}",
      cambiar_fecha: "Change date",
      moverte: "Can you move your trip a month?",
      alt_eyebrow: "Same Caribbean, fewer people",
      alt_titulo: "What about <em>{d}?</em>",
      alt_boton: "See {d} on {f}",
      nivel_el: "{n} on {f}",
      cuando_eyebrow: "When to go",
      cuando_titulo: "The year, <em>wave by wave.</em>",
      cuando_nota: "The taller and redder the wave, the busier it gets. Tap a month to see what it's like.",
      mejores: "The quietest dates for {d}",
      planear_mes: "Plan {m} →",
      dia_eyebrow: "Your perfect day",
      dia_titulo: "Every place has <em>its hour.</em>",
      manana: "Morning", tarde: "Afternoon", noche: "Night",
      ve_de: "Go in the {m}",
      lugares_eyebrow: "Things to do",
      lugares_titulo: "Must-sees in <em>{d}</em>",
      posible_sargazo: "Possible sargassum",
      tipos: { cultura: "Maya culture", naturaleza: "Nature", mar: "Sea", playa: "Beach", cenote: "Cenote", comida: "Dinner spot" },
      postales_eyebrow: "Postcards",
      postales_titulo: "This is <em>Quintana Roo.</em>",
      comida_eyebrow: "What to eat",
      comida_titulo: "Taste <em>the peninsula.</em>",
      comida_consejos: "Tips for eating well",
      donde_comer: "Where to eat in {d}",
      osm_nota: "OpenStreetMap list, regional cooking first. Tap “See reviews” for its Google Maps rating.",
      moverse_eyebrow: "Getting around",
      moverse_titulo: "North to south, <em>unhurried.</em>",
      faq_eyebrow: "Frequently asked",
      faq_titulo: "What everyone <em>asks.</em>",
      destinos_eyebrow: "Three destinations",
      destinos_titulo: "One state, <em>three rhythms.</em>",
      region_de: "{r} Quintana Roo",
      con_calma: "For a calm trip: {m}.",
      planear_aqui: "Plan here",
      pie_grande: "Stay <em>the night.</em>",
      pie_nota: "Predictions are estimates built from official Quintana Roo tourism data.",
      creditos: "Credits",
      osm_credito: "Restaurants: © OpenStreetMap contributors (ODbL)",
      autoridades: "For authorities: CAUCE system ↗",
      sin_conexion_t: "Offline", sin_conexion_x: "We couldn't load the forecast.",
      idioma: "Language",
      ev_mas_t: "One of the busiest times of the year", ev_mas_x: "{m} is a favorite month to visit {d}.",
      ev_menos_t: "One of the quietest times of the year", ev_menos_x: "Few travelers pick {m}: you'll have more room.",
      ev_vac_x: "Many Mexican families travel that week: expect more people even in a quiet month. Book early.",
      ev_puente_t: "Long weekend", ev_puente_x: "{f}: more Mexican families on the road.",
      ev_festivo_x: "There's a public holiday close to your date.",
      ev_finde_t: "It's a weekend", ev_finde_x: "Famous spots are roomier on weekdays.",
      ev_sarg_alto_t: "Sargassum season", ev_sarg_alto_x: "Seaweed may reach the beaches. Bacalar lagoon and the cenotes stay perfect.",
      ev_sarg_medio_t: "Some sargassum possible", ev_sarg_medio_x: "A few beaches could have seaweed those days.",
      ev_visit_t: "About {n} thousand visitors", ev_visit_x: "arrive in {d} during {m}.",
      argumento: {
        gran_costa_maya: "Bacalar lagoon, cenotes and Maya ruins in the jungle, with a fraction of the crowds. This is where you stay the night.",
        riviera_maya: "Seaside ruins, cenotes and the Sian Ka'an reserve, with fewer people that month.",
        cancun: "Open Caribbean beaches, El Rey Maya site and more free rooms that month.",
      },
      mov_bus: "Arrive by bus", mov_tren: "…or on the Tren Maya", mov_avion: "…or fly straight in", mov_bienvenida: "Welcome to Quintana Roo",
      dormir_eyebrow: "Where to stay", dormir_titulo: "Stay <em>the night.</em>", todas: "All", ver_resenas: "See reviews on Google Maps", resenas_nota: "Ratings and reviews open directly on Google Maps: you'll see the stars (1 to 5) and how many people reviewed. A 4.5 with hundreds of reviews says more than a 5 with three. List from OpenStreetMap; not a ranking.", tipo_hotel: "Hotel", tipo_hostel: "Hostel", tipo_guest_house: "Guest house", estrellas_cat: "{n}-star category", sitio_web: "Website",
      bot_titulo: "Ask Temporada", bot_sub: "Instant answers about Quintana Roo",
      bot_placeholder: "Type your question…", bot_enviar: "Send", bot_abrir: "Open assistant", bot_cerrar: "Close assistant",
    },
    fr: {
      saltar: "Aller à la recherche",
      nav_como: "À quoi s'attendre", nav_cuando: "Quand partir", nav_hacer: "À faire", nav_comer: "Cuisine", nav_faq: "Questions",
      vuelos_barra: "Chercher des vols",
      antetitulo: "Quintana Roo · Cancún · Riviera Maya · Bacalar",
      titular: "Arrive quand la mer <em>est à toi.</em>",
      bajada: "Dis-nous où et quand tu veux partir. On te montre l'affluence, ce qui se passe ces jours-là et quoi faire.",
      frase_ir: "Je veux aller à", frase_el: "le", placeholder: "15 janvier", ver: "Voir comment ce sera",
      prueba: "Essaie :", sugerencias: ["Semaine sainte", "Été", "Noël", "Octobre"],
      cal_titulo: "Quel mois ?", cal_ayuda: "Les petites vagues montrent l'affluence habituelle.",
      cal_festivo: "Jour férié", cal_vacaciones: "Vacances au Mexique", cal_finde: "Week-end", cal_cerrar: "Fermer le calendrier",
      abrir_cal: "Choisir sur le calendrier", fecha_label: "Date du voyage",
      pista_mes: "ou choisis le jour sur le calendrier",
      err_fecha: "Date non comprise. Essaie « 15 janvier », « mars » ou « Semaine sainte ».",
      err_pasada: "Cette date est passée. Choisis-en une à venir.",
      err_rango: "Pour l'instant, tu peux planifier jusqu'à décembre 2027.",
      err_vacia: "Écris une date, par exemple « 15 janvier ».",
      playa_caption: "Voici l'ambiance sur la plage ce jour-là",
      playa_ayuda: "Survole ou touche pour comparer",
      playa_ventanas: "Fenêtres allumées = chambres d'hôtel occupées",
      estara: "{d} sera",
      vuelos_a: "Vols vers {c} · {f}",
      cambiar_fecha: "Changer de date",
      moverte: "Peux-tu décaler d'un mois ?",
      alt_eyebrow: "Même Caraïbe, moins de monde",
      alt_titulo: "Et si tu allais plutôt à <em>{d} ?</em>",
      alt_boton: "Voir {d} le {f}",
      nivel_el: "{n} le {f}",
      cuando_eyebrow: "Quand partir",
      cuando_titulo: "L'année, <em>vague par vague.</em>",
      cuando_nota: "Plus la vague est haute et rouge, plus il y a de monde. Touche un mois pour voir.",
      mejores: "Les dates les plus calmes pour {d}",
      planear_mes: "Planifier {m} →",
      dia_eyebrow: "Ta journée idéale",
      dia_titulo: "Chaque lieu a <em>son heure.</em>",
      manana: "Matin", tarde: "Après-midi", noche: "Soir",
      ve_de: "Y aller le {m}",
      lugares_eyebrow: "À faire",
      lugares_titulo: "Incontournables de <em>{d}</em>",
      posible_sargazo: "Sargasses possibles",
      tipos: { cultura: "Culture maya", naturaleza: "Nature", mar: "Mer", playa: "Plage", cenote: "Cénote", comida: "Pour dîner" },
      postales_eyebrow: "Cartes postales",
      postales_titulo: "Voici <em>le Quintana Roo.</em>",
      comida_eyebrow: "Quoi goûter",
      comida_titulo: "La péninsule <em>se déguste.</em>",
      comida_consejos: "Conseils pour bien manger",
      donde_comer: "Où manger à {d}",
      osm_nota: "Liste OpenStreetMap, cuisine régionale d'abord. Touche « Voir les avis » pour sa note Google Maps.",
      moverse_eyebrow: "Se déplacer",
      moverse_titulo: "Du nord au sud, <em>sans se presser.</em>",
      faq_eyebrow: "Questions fréquentes",
      faq_titulo: "Ce que tout le monde <em>demande.</em>",
      destinos_eyebrow: "Trois destinations",
      destinos_titulo: "Un État, <em>trois rythmes.</em>",
      region_de: "{r} du Quintana Roo",
      con_calma: "Pour un séjour tranquille : {m}.",
      planear_aqui: "Planifier ici",
      pie_grande: "Reste <em>pour la nuit.</em>",
      pie_nota: "Les prévisions sont des estimations fondées sur les données officielles du tourisme du Quintana Roo.",
      creditos: "Crédits",
      osm_credito: "Restaurants : © contributeurs d'OpenStreetMap (ODbL)",
      autoridades: "Pour les autorités : système CAUCE ↗",
      sin_conexion_t: "Hors ligne", sin_conexion_x: "Impossible de charger la prévision.",
      idioma: "Langue",
      ev_mas_t: "L'une des périodes les plus fréquentées", ev_mas_x: "{m} est un mois très prisé pour {d}.",
      ev_menos_t: "L'une des périodes les plus calmes", ev_menos_x: "Peu de voyageurs choisissent {m} : tu auras plus d'espace.",
      ev_vac_x: "Beaucoup de familles mexicaines voyagent cette semaine-là : plus de monde même si le mois est calme. Réserve tôt.",
      ev_puente_t: "Week-end prolongé", ev_puente_x: "{f} : plus de familles mexicaines en voyage.",
      ev_festivo_x: "Un jour férié tombe près de ta date.",
      ev_finde_t: "C'est le week-end", ev_finde_x: "En semaine, les lieux célèbres sont moins bondés.",
      ev_sarg_alto_t: "Saison des sargasses", ev_sarg_alto_x: "Des algues peuvent arriver sur les plages. La lagune de Bacalar et les cénotes restent parfaits.",
      ev_sarg_medio_t: "Sargasses possibles", ev_sarg_medio_x: "Quelques plages pourraient avoir des algues ces jours-là.",
      ev_visit_t: "Environ {n} mille visiteurs", ev_visit_x: "arrivent à {d} en {m}.",
      argumento: {
        gran_costa_maya: "La lagune de Bacalar, des cénotes et des sites mayas dans la jungle, avec une fraction du monde. Ici, on reste pour la nuit.",
        riviera_maya: "Ruines face à la mer, cénotes et la réserve de Sian Ka'an, avec moins de monde ce mois-là.",
        cancun: "Plages ouvertes sur la Caraïbe, le site maya El Rey et plus de chambres libres ce mois-là.",
      },
      mov_bus: "Arrive en bus", mov_tren: "…ou en Tren Maya", mov_avion: "…ou en avion", mov_bienvenida: "Bienvenue au Quintana Roo",
      dormir_eyebrow: "Où dormir", dormir_titulo: "Reste <em>pour la nuit.</em>", todas: "Toutes", ver_resenas: "Voir les avis sur Google Maps", resenas_nota: "Les notes et avis s'ouvrent directement sur Google Maps : tu y verras les étoiles (1 à 5) et le nombre d'avis. Un 4,5 avec des centaines d'avis en dit plus qu'un 5 avec trois. Liste OpenStreetMap ; ce n'est pas un classement.", tipo_hotel: "Hôtel", tipo_hostel: "Auberge", tipo_guest_house: "Maison d'hôtes", estrellas_cat: "Catégorie {n} étoiles", sitio_web: "Site web",
      bot_titulo: "Demande à Temporada", bot_sub: "Réponses immédiates sur le Quintana Roo",
      bot_placeholder: "Écris ta question…", bot_enviar: "Envoyer", bot_abrir: "Ouvrir l'assistant", bot_cerrar: "Fermer l'assistant",
    },
    pt: {
      saltar: "Ir para a busca",
      nav_como: "Como vai estar", nav_cuando: "Quando ir", nav_hacer: "O que fazer", nav_comer: "Comida", nav_faq: "Perguntas",
      vuelos_barra: "Buscar voos",
      antetitulo: "Quintana Roo · Cancún · Riviera Maya · Bacalar",
      titular: "Chegue quando o mar <em>for seu.</em>",
      bajada: "Diga para onde e quando quer ir. Mostramos quanta gente vai ter, o que acontece nesses dias e o que fazer.",
      frase_ir: "Quero ir para", frase_el: "em", placeholder: "15 de janeiro", ver: "Ver como vai estar",
      prueba: "Experimente:", sugerencias: ["Semana Santa", "Verão", "Natal", "Outubro"],
      cal_titulo: "Qual mês?", cal_ayuda: "As ondinhas mostram quanta gente costuma ter.",
      cal_festivo: "Feriado", cal_vacaciones: "Férias no México", cal_finde: "Fim de semana", cal_cerrar: "Fechar calendário",
      abrir_cal: "Escolher no calendário", fecha_label: "Data da viagem",
      pista_mes: "ou escolha o dia no calendário",
      err_fecha: "Não entendemos essa data. Tente “15 de janeiro”, “março” ou “Semana Santa”.",
      err_pasada: "Essa data já passou. Escolha uma próxima.",
      err_rango: "Por enquanto dá para planejar até dezembro de 2027.",
      err_vacia: "Escreva uma data, por exemplo “15 de janeiro”.",
      playa_caption: "Assim estaria a praia nesse dia",
      playa_ayuda: "Passe o cursor ou toque para comparar",
      playa_ventanas: "Janelas acesas = quartos de hotel ocupados",
      estara: "{d} vai estar",
      vuelos_a: "Voos para {c} · {f}",
      cambiar_fecha: "Mudar data",
      moverte: "Dá para mudar a viagem um mês?",
      alt_eyebrow: "Mesmo Caribe, menos gente",
      alt_titulo: "E se você for para <em>{d}?</em>",
      alt_boton: "Ver {d} em {f}",
      nivel_el: "{n} em {f}",
      cuando_eyebrow: "Quando ir",
      cuando_titulo: "O ano, <em>onda por onda.</em>",
      cuando_nota: "Quanto mais alta e vermelha a onda, mais gente. Toque um mês para ver.",
      mejores: "As datas mais tranquilas para {d}",
      planear_mes: "Planejar {m} →",
      dia_eyebrow: "Seu dia ideal",
      dia_titulo: "Cada lugar tem <em>sua hora.</em>",
      manana: "Manhã", tarde: "Tarde", noche: "Noite",
      ve_de: "Vá de {m}",
      lugares_eyebrow: "O que fazer",
      lugares_titulo: "Imperdíveis de <em>{d}</em>",
      posible_sargazo: "Possível sargaço",
      tipos: { cultura: "Cultura maia", naturaleza: "Natureza", mar: "Mar", playa: "Praia", cenote: "Cenote", comida: "Para jantar" },
      postales_eyebrow: "Cartões-postais",
      postales_titulo: "Este é <em>Quintana Roo.</em>",
      comida_eyebrow: "O que provar",
      comida_titulo: "A península <em>se come.</em>",
      comida_consejos: "Dicas para comer bem",
      donde_comer: "Onde comer em {d}",
      osm_nota: "Lista do OpenStreetMap com prioridade à cozinha regional. Toque em “Ver avaliações” para ver a nota no Google Maps.",
      moverse_eyebrow: "Como se locomover",
      moverse_titulo: "Do norte ao sul, <em>sem pressa.</em>",
      faq_eyebrow: "Perguntas frequentes",
      faq_titulo: "O que todo mundo <em>pergunta.</em>",
      destinos_eyebrow: "Três destinos",
      destinos_titulo: "Um estado, <em>três ritmos.</em>",
      region_de: "{r} de Quintana Roo",
      con_calma: "Para ir com calma: {m}.",
      planear_aqui: "Planejar aqui",
      pie_grande: "Fique <em>a noite.</em>",
      pie_nota: "As previsões são estimativas feitas com dados oficiais de turismo de Quintana Roo.",
      creditos: "Créditos",
      osm_credito: "Restaurantes: © colaboradores do OpenStreetMap (ODbL)",
      autoridades: "Para autoridades: sistema CAUCE ↗",
      sin_conexion_t: "Sem conexão", sin_conexion_x: "Não foi possível carregar a previsão.",
      idioma: "Idioma",
      ev_mas_t: "Uma das épocas mais cheias do ano", ev_mas_x: "{m} é um dos meses favoritos para ir a {d}.",
      ev_menos_t: "Uma das épocas mais tranquilas do ano", ev_menos_x: "Poucos viajantes escolhem {m}: você terá mais espaço.",
      ev_vac_x: "Muitas famílias mexicanas viajam nessa semana: aumenta o movimento mesmo num mês tranquilo. Reserve cedo.",
      ev_puente_t: "Feriado prolongado", ev_puente_x: "{f}: mais famílias mexicanas viajando.",
      ev_festivo_x: "Há um feriado perto da sua data.",
      ev_finde_t: "Cai no fim de semana", ev_finde_x: "Durante a semana os lugares famosos ficam mais vazios.",
      ev_sarg_alto_t: "Temporada de sargaço", ev_sarg_alto_x: "Pode chegar alga às praias. A lagoa de Bacalar e os cenotes continuam perfeitos.",
      ev_sarg_medio_t: "Pode haver sargaço", ev_sarg_medio_x: "Algumas praias podem ter alga nesses dias.",
      ev_visit_t: "Chegam cerca de {n} mil visitantes", ev_visit_x: "a {d} em {m}.",
      argumento: {
        gran_costa_maya: "A lagoa de Bacalar, cenotes e ruínas maias na selva, com uma fração da gente. Aqui você passa a noite.",
        riviera_maya: "Ruínas à beira-mar, cenotes e a reserva de Sian Ka'an, com menos gente nesse mês.",
        cancun: "Praias abertas para o Caribe, o sítio maia El Rey e mais quartos livres nesse mês.",
      },
      mov_bus: "Chegue de ônibus", mov_tren: "…ou de Tren Maya", mov_avion: "…ou voe direto", mov_bienvenida: "Bem-vindo a Quintana Roo",
      dormir_eyebrow: "Onde dormir", dormir_titulo: "Fique <em>a noite.</em>", todas: "Todas", ver_resenas: "Ver avaliações no Google Maps", resenas_nota: "As notas e avaliações abrem direto no Google Maps: lá você vê as estrelas (1 a 5) e quantas pessoas avaliaram. Um 4,5 com centenas de avaliações diz mais que um 5 com três. Lista do OpenStreetMap; não é um ranking.", tipo_hotel: "Hotel", tipo_hostel: "Hostel", tipo_guest_house: "Pousada", estrellas_cat: "Categoria {n} estrelas", sitio_web: "Site",
      bot_titulo: "Pergunte à Temporada", bot_sub: "Respostas instantâneas sobre Quintana Roo",
      bot_placeholder: "Escreva sua pergunta…", bot_enviar: "Enviar", bot_abrir: "Abrir assistente", bot_cerrar: "Fechar assistente",
    },
  },

  niveles: {
    es: { tranquilo: ["Tranquilo", "Tranquilo", "Playas amplias, sin filas y mejores precios."], moderado: ["Con buen ambiente", "Buen ambiente", "Hay gente, pero se disfruta sin prisas."], concurrido: ["Muy concurrido", "Concurrido", "Mucha gente en los lugares famosos. Reserva con tiempo."], lleno: ["A reventar", "Lleno", "Casi todos los hoteles llenos. Mejor otra fecha u otro destino."] },
    en: { tranquilo: ["Quiet", "Quiet", "Wide-open beaches, no lines and better prices."], moderado: ["Nicely lively", "Lively", "Some people around, still easygoing."], concurrido: ["Very busy", "Busy", "Crowds at the famous spots. Book ahead."], lleno: ["Packed", "Packed", "Hotels almost full. Try another date or destination."] },
    fr: { tranquilo: ["Calme", "Calme", "Plages dégagées, pas de file et de meilleurs prix."], moderado: ["Bonne ambiance", "Animé", "Du monde, mais on en profite sans stress."], concurrido: ["Très fréquenté", "Fréquenté", "Foule aux endroits célèbres. Réserve à l'avance."], lleno: ["Complet", "Complet", "Hôtels presque pleins. Mieux vaut une autre date ou destination."] },
    pt: { tranquilo: ["Tranquilo", "Tranquilo", "Praias amplas, sem filas e com preços melhores."], moderado: ["Bom movimento", "Movimentado", "Tem gente, mas dá para curtir sem pressa."], concurrido: ["Muito cheio", "Cheio", "Muita gente nos lugares famosos. Reserve com antecedência."], lleno: ["Lotado", "Lotado", "Hotéis quase lotados. Melhor outra data ou destino."] },
  },

  festivos: {
    en: { "Año Nuevo": "New Year's Day", "Día de la Constitución (puente)": "Constitution Day (long weekend)", "Natalicio de Benito Juárez (puente)": "Benito Juárez's Birthday (long weekend)", "Jueves Santo": "Holy Thursday", "Viernes Santo": "Good Friday", "Día del Trabajo": "Labor Day", "Día de la Independencia": "Independence Day", "Revolución Mexicana (puente)": "Revolution Day (long weekend)", "Navidad": "Christmas", "Semana Santa y Pascua": "Holy Week & Easter", "Vacaciones de invierno (periodo aproximado)": "Winter holidays" },
    fr: { "Año Nuevo": "Jour de l'An", "Día de la Constitución (puente)": "Fête de la Constitution (pont)", "Natalicio de Benito Juárez (puente)": "Anniversaire de Benito Juárez (pont)", "Jueves Santo": "Jeudi saint", "Viernes Santo": "Vendredi saint", "Día del Trabajo": "Fête du Travail", "Día de la Independencia": "Fête de l'Indépendance", "Revolución Mexicana (puente)": "Fête de la Révolution (pont)", "Navidad": "Noël", "Semana Santa y Pascua": "Semaine sainte et Pâques", "Vacaciones de invierno (periodo aproximado)": "Vacances d'hiver" },
    pt: { "Año Nuevo": "Ano-Novo", "Día de la Constitución (puente)": "Dia da Constituição (feriado prolongado)", "Natalicio de Benito Juárez (puente)": "Aniversário de Benito Juárez (feriado prolongado)", "Jueves Santo": "Quinta-feira Santa", "Viernes Santo": "Sexta-feira Santa", "Día del Trabajo": "Dia do Trabalho", "Día de la Independencia": "Dia da Independência", "Revolución Mexicana (puente)": "Dia da Revolução (feriado prolongado)", "Navidad": "Natal", "Semana Santa y Pascua": "Semana Santa e Páscoa", "Vacaciones de invierno (periodo aproximado)": "Férias de inverno" },
  },

  // Palabras de fecha en otros idiomas -> español, para el intérprete.
  fechas_palabras: {
    january: "enero", february: "febrero", march: "marzo", april: "abril", may: "mayo", june: "junio", july: "julio", august: "agosto", september: "septiembre", october: "octubre", november: "noviembre", december: "diciembre",
    jan: "ene", feb: "feb", apr: "abr", aug: "ago", sep: "sep", sept: "sep", oct: "oct", nov: "nov", dec: "dic",
    janvier: "enero", fevrier: "febrero", mars: "marzo", avril: "abril", mai: "mayo", juin: "junio", juillet: "julio", aout: "agosto", septembre: "septiembre", octobre: "octubre", novembre: "noviembre", decembre: "diciembre",
    janeiro: "enero", fevereiro: "febrero", marco: "marzo", maio: "mayo", junho: "junio", julho: "julio", setembro: "septiembre", outubro: "octubre", novembro: "noviembre", dezembro: "diciembre",
    "holy week": "semana santa", "semaine sainte": "semana santa", easter: "pascua", paques: "pascua", pascoa: "pascua",
    christmas: "navidad", noel: "navidad", natal: "navidad", "new year": "ano nuevo", "nouvel an": "ano nuevo", "ano-novo": "ano nuevo", reveillon: "fin de ano",
    summer: "verano", ete: "verano", verao: "verano", "day of the dead": "dia de muertos", toussaint: "dia de muertos", finados: "dia de muertos",
  },

  destinos: {
    en: { cancun: ["North", "The Caribbean everyone knows"], riviera_maya: ["Central", "Seaside ruins and jungle cenotes"], gran_costa_maya: ["South", "Stay the night"] },
    fr: { cancun: ["Nord", "La Caraïbe que tout le monde connaît"], riviera_maya: ["Centre", "Ruines face à la mer et cénotes"], gran_costa_maya: ["Sud", "Reste pour la nuit"] },
    pt: { cancun: ["Norte", "O Caribe que todo mundo conhece"], riviera_maya: ["Centro", "Ruínas à beira-mar e cenotes"], gran_costa_maya: ["Sul", "Fique a noite"] },
  },

  // Traducciones de lugares (el español viene de lugares.yaml vía el planeador).
  lugares: {
    en: {
      el_rey: ["El Rey Archaeological Site", "Post-Classic Maya ruins right in the hotel zone, between Nichupté lagoon and the sea. Platforms, a causeway and lots of iguanas.", "There's almost no shade. Go first thing and bring water."],
      museo_maya_cancun: ["Maya Museum of Cancún & San Miguelito", "INAH museum with regional archaeological pieces and, on the same grounds, the San Miguelito Maya site in the jungle.", "A great plan for the hottest hours."],
      musa: ["Underwater Museum of Art (MUSA)", "Submerged sculptures off Cancún that work as an artificial reef. Seen by snorkel or diving.", "Mornings usually bring calmer water and better visibility."],
      playa_delfines: ["Playa Delfines (El Mirador)", "Public beach in the hotel zone, open to the Caribbean, with the lookout and the Cancún letters.", "Waves are strong; follow the lifeguard flags."],
      parque_palapas: ["Parque de las Palapas", "Downtown Cancún's plaza, where local families have dinner: marquesitas, esquites and street snacks.", "Lively at night, especially on weekends."],
      tulum_ruinas: ["Tulum Archaeological Site", "A walled Maya city on a cliff above the Caribbean. El Castillo rules the coast.", "Arrive at opening time, before the tour groups."],
      coba: ["Cobá", "An ancient Maya city among lagoons and jungle, linked by sacbés (white roads) you can ride by bike. Nohoch Mul is one of the peninsula's tallest pyramids.", "Rent a bike at the entrance; the groups are far apart."],
      sian_kaan: ["Sian Ka'an Biosphere Reserve", "UNESCO World Heritage. Jungle, mangroves, lagoons and Maya canals you float down with the current.", "Hire guides from the reserve's local cooperatives."],
      akumal: ["Akumal Bay", "A bay known for sea turtles grazing on seagrass near the shore.", "Swimming with turtles is regulated; go with a guide and never touch them."],
      dos_ojos: ["Dos Ojos Cenote", "Two cenotes joined by one of the longest underwater cave systems in the world. Crystal-clear snorkeling and cavern diving.", "Around midday, light pours into the water in beams."],
      quinta_avenida: ["Fifth Avenue, Playa del Carmen", "The pedestrian street parallel to the sea: shops, cafés and restaurants open late.", "Side streets toward downtown have more local options."],
      puerto_morelos: ["Puerto Morelos", "A fishing village with a leaning lighthouse and a national-park reef just off the shore.", "The reef is protected: snorkel only with authorized operators."],
      laguna_bacalar: ["Bacalar Lagoon", "The lagoon of seven colors. Fresh water over white sand, shifting from turquoise to navy with depth. Caribbean sargassum doesn't reach it.", "In the morning the water is stiller and the colors pop."],
      estromatolitos: ["Bacalar Stromatolites", "Living structures built by microorganisms, relatives of the oldest life forms on Earth. Visible from shore at spots like Cocalitos.", "Don't step on or touch them. Use biodegradable sunscreen."],
      canal_piratas: ["Pirates' Channel by sailboat", "The passage pirates used to enter the lagoon. Boat and sailboat tours also stop at Bird Island and Cenote Esmeralda.", "Motorless sailboats are the quietest way to see the lagoon."],
      cenote_azul: ["Cenote Azul", "A huge open cenote, about 90 meters deep, by the road at the entrance to Bacalar.", "Perfect for a swim after lunch, when the heat peaks."],
      fuerte_san_felipe: ["San Felipe Fort", "An 18th-century fortress built to defend Bacalar from pirates. Now a museum and lagoon lookout.", "Climb the wall late in the afternoon to watch the lagoon change color."],
      mahahual: ["Mahahual Boardwalk", "A fishing village facing the Mesoamerican Reef. Cruise ships come by day; at night the boardwalk is calm for dinner by the sea.", "Stay the night. When the ships leave, the town is yours again."],
      banco_chinchorro: ["Banco Chinchorro", "A biosphere reserve and Mexico's largest coral atoll, with shipwrecks among its reefs. Trips leave from Mahahual.", "Departures depend on weather; book with a day to spare."],
      chacchoben: ["Chacchobén Archaeological Site", "Maya temples hidden in the jungle, with ancient trees and howler monkeys around.", "Arrive at opening to have it almost to yourself."],
      kohunlich: ["Kohunlich", "Famous for the Temple of the Masks, several-meter-tall stucco faces looking east.", "Pair it with Dzibanché the same day; they're on the same route."],
      dzibanche: ["Dzibanché", "One of southern Quintana Roo's great Maya capitals, deep in the jungle and with very few visitors.", "Bring repellent; the jungle is dense."],
      museo_cultura_maya: ["Museum of Maya Culture", "In Chetumal. Walk through the Maya worldview on three levels, from the underworld to the sky.", "A good refuge for the hottest hours."],
      boulevard_bahia: ["Chetumal Bay Boardwalk", "The capital's waterfront, facing the bay where manatees live. At night it fills with families, food stands and breeze.", "Try salbutes at the stands near the boardwalk."],
    },
    fr: {
      el_rey: ["Site archéologique El Rey", "Ruines mayas postclassiques en pleine zone hôtelière, entre la lagune Nichupté et la mer. Plateformes, chaussée et beaucoup d'iguanes.", "Presque pas d'ombre. Viens tôt et apporte de l'eau."],
      museo_maya_cancun: ["Musée maya de Cancún et San Miguelito", "Musée de l'INAH avec des pièces archéologiques régionales et, dans le même lieu, le site maya de San Miguelito dans la jungle.", "Parfait pour les heures les plus chaudes."],
      musa: ["Musée sous-marin d'art (MUSA)", "Sculptures immergées au large de Cancún qui servent de récif artificiel. À voir en snorkeling ou en plongée.", "Le matin, la mer est souvent plus calme et plus claire."],
      playa_delfines: ["Playa Delfines (El Mirador)", "Plage publique de la zone hôtelière, ouverte sur la Caraïbe, avec le belvédère et les lettres de Cancún.", "Les vagues sont fortes ; respecte les drapeaux des sauveteurs."],
      parque_palapas: ["Parc de las Palapas", "La place du centre de Cancún où dînent les familles : marquesitas, esquites et en-cas.", "Très animé le soir, surtout le week-end."],
      tulum_ruinas: ["Site archéologique de Tulum", "Cité maya fortifiée sur une falaise face à la Caraïbe. El Castillo domine la côte.", "Arrive à l'ouverture, avant les groupes."],
      coba: ["Cobá", "Ancienne cité maya entre lagunes et jungle, reliée par des sacbés (chemins blancs) à parcourir à vélo. Nohoch Mul est l'une des plus hautes pyramides de la péninsule.", "Loue un vélo à l'entrée ; les distances sont longues."],
      sian_kaan: ["Réserve de biosphère de Sian Ka'an", "Patrimoine mondial de l'UNESCO. Jungle, mangroves, lagunes et canaux mayas où l'on flotte avec le courant.", "Fais appel aux guides des coopératives locales."],
      akumal: ["Baie d'Akumal", "Baie connue pour ses tortues marines qui broutent les herbiers près du rivage.", "La nage avec les tortues est réglementée : avec un guide et sans les toucher."],
      dos_ojos: ["Cénote Dos Ojos", "Deux cénotes reliés par l'un des plus longs réseaux de grottes inondées du monde. Snorkeling cristallin et plongée en caverne.", "Vers midi, la lumière entre en faisceaux dans l'eau."],
      quinta_avenida: ["Cinquième Avenue, Playa del Carmen", "La rue piétonne parallèle à la mer : boutiques, cafés et restaurants ouverts tard.", "Les rues vers le centre offrent des options plus locales."],
      puerto_morelos: ["Puerto Morelos", "Village de pêcheurs avec son phare penché et un récif de parc national à quelques mètres du rivage.", "Le récif est protégé : snorkeling uniquement avec des prestataires agréés."],
      laguna_bacalar: ["Lagune de Bacalar", "La lagune aux sept couleurs. Eau douce sur sable blanc, du turquoise au bleu marine selon la profondeur. Les sargasses n'y arrivent pas.", "Le matin, l'eau est plus calme et les couleurs ressortent mieux."],
      estromatolitos: ["Stromatolithes de Bacalar", "Structures vivantes formées par des micro-organismes, parents des plus anciennes formes de vie. Visibles depuis la rive, comme à Cocalitos.", "On ne marche pas dessus. Utilise une crème solaire biodégradable."],
      canal_piratas: ["Canal des Pirates en voilier", "Le passage qu'utilisaient les pirates pour entrer dans la lagune. Les sorties passent aussi par l'île aux Oiseaux et le cénote Esmeralda.", "Les voiliers sans moteur sont l'option la plus silencieuse."],
      cenote_azul: ["Cénote Azul", "Un immense cénote ouvert d'environ 90 mètres de profondeur, au bord de la route à l'entrée de Bacalar.", "Idéal pour nager après le déjeuner, quand il fait le plus chaud."],
      fuerte_san_felipe: ["Fort San Felipe", "Forteresse du XVIIIe siècle construite pour défendre Bacalar des pirates. Aujourd'hui musée et belvédère.", "Monte sur la muraille en fin d'après-midi pour voir la lagune changer de couleur."],
      mahahual: ["Promenade de Mahahual", "Village de pêcheurs face au Récif mésoaméricain. Le jour arrivent les croisières ; le soir, la promenade est paisible.", "Reste pour la nuit. Quand les bateaux partent, le village est à toi."],
      banco_chinchorro: ["Banco Chinchorro", "Réserve de biosphère et plus grand atoll corallien du Mexique, avec des épaves parmi les récifs. Départs depuis Mahahual.", "Les sorties dépendent de la météo ; réserve avec un jour de marge."],
      chacchoben: ["Site archéologique de Chacchobén", "Temples mayas cachés dans la jungle, entourés d'arbres centenaires et de singes hurleurs.", "Arrive à l'ouverture pour l'avoir presque pour toi."],
      kohunlich: ["Kohunlich", "Célèbre pour le Temple des Masques, des visages en stuc de plusieurs mètres tournés vers l'est.", "Combine-le avec Dzibanché le même jour."],
      dzibanche: ["Dzibanché", "L'une des grandes capitales mayas du sud du Quintana Roo, en pleine jungle et très peu visitée.", "Emporte du répulsif ; la jungle est dense."],
      museo_cultura_maya: ["Musée de la culture maya", "À Chetumal. La vision maya du monde sur trois niveaux, de l'inframonde au ciel.", "Un bon refuge aux heures chaudes."],
      boulevard_bahia: ["Boulevard de la baie de Chetumal", "Le front de mer de la capitale, face à la baie où vit le lamantin. Le soir, familles, stands et brise.", "Goûte les salbutes aux stands près du front de mer."],
    },
    pt: {
      el_rey: ["Zona Arqueológica El Rey", "Ruínas maias do período pós-clássico em plena zona hoteleira, entre a lagoa Nichupté e o mar. Plataformas, uma calçada e muitas iguanas.", "Quase não há sombra. Vá cedo e leve água."],
      museo_maya_cancun: ["Museu Maia de Cancún e San Miguelito", "Museu do INAH com peças arqueológicas da região e, no mesmo local, o sítio maia de San Miguelito na selva.", "Ótimo programa para as horas mais quentes."],
      musa: ["Museu Subaquático de Arte (MUSA)", "Esculturas submersas na costa de Cancún que funcionam como recife artificial. Vistas com snorkel ou mergulho.", "De manhã costuma haver menos ondas e melhor visibilidade."],
      playa_delfines: ["Playa Delfines (El Mirador)", "Praia pública da zona hoteleira, aberta ao Caribe, com o mirante e as letras de Cancún.", "As ondas são fortes; respeite as bandeiras dos salva-vidas."],
      parque_palapas: ["Parque de las Palapas", "A praça do centro de Cancún onde as famílias jantam: marquesitas, esquites e petiscos.", "Animado à noite, sobretudo no fim de semana."],
      tulum_ruinas: ["Zona Arqueológica de Tulum", "Cidade maia murada sobre um penhasco diante do Caribe. El Castillo domina a costa.", "Chegue na abertura, antes dos grupos de excursão."],
      coba: ["Cobá", "Antiga cidade maia entre lagoas e selva, ligada por sacbés (caminhos brancos) percorridos de bicicleta. Nohoch Mul é uma das pirâmides mais altas da península.", "Alugue bicicleta na entrada; as distâncias são longas."],
      sian_kaan: ["Reserva da Biosfera Sian Ka'an", "Patrimônio Mundial da UNESCO. Selva, manguezal, lagoas e canais maias para flutuar com a correnteza.", "Contrate guias das cooperativas locais."],
      akumal: ["Baía de Akumal", "Baía conhecida pelas tartarugas marinhas que se alimentam de ervas marinhas perto da praia.", "Nadar com tartarugas é regulamentado; vá com guia e sem tocar nos animais."],
      dos_ojos: ["Cenote Dos Ojos", "Dois cenotes unidos por um dos maiores sistemas de cavernas inundadas do mundo. Snorkel em água cristalina e mergulho em caverna.", "Perto do meio-dia a luz entra em feixes na água."],
      quinta_avenida: ["Quinta Avenida, Playa del Carmen", "A rua de pedestres paralela ao mar: lojas, cafés e restaurantes abertos até tarde.", "As ruas transversais rumo ao centro têm opções mais locais."],
      puerto_morelos: ["Puerto Morelos", "Vila de pescadores com seu farol inclinado e um recife de parque nacional a poucos metros da praia.", "O recife é protegido: snorkel só com operadores autorizados."],
      laguna_bacalar: ["Lagoa de Bacalar", "A lagoa das sete cores. Água doce sobre areia branca, do turquesa ao azul-marinho conforme a profundidade. O sargaço do Caribe não chega aqui.", "De manhã a água está mais calma e as cores brilham mais."],
      estromatolitos: ["Estromatólitos de Bacalar", "Estruturas vivas formadas por microrganismos, parentes das formas de vida mais antigas do planeta. Vistos da margem, como em Cocalitos.", "Não pise nem toque. Use protetor solar biodegradável."],
      canal_piratas: ["Canal dos Piratas de veleiro", "A passagem que os piratas usavam para entrar na lagoa. Os passeios também passam pela Ilha dos Pássaros e pelo Cenote Esmeralda.", "Veleiros sem motor são a opção mais silenciosa."],
      cenote_azul: ["Cenote Azul", "Um enorme cenote aberto, com cerca de 90 metros de profundidade, à beira da estrada na entrada de Bacalar.", "Ideal para nadar depois do almoço, quando o calor aperta."],
      fuerte_san_felipe: ["Forte de San Felipe", "Fortaleza do século XVIII construída para defender Bacalar dos piratas. Hoje é museu e mirante.", "Suba na muralha no fim da tarde para ver a lagoa mudar de cor."],
      mahahual: ["Calçadão de Mahahual", "Vila de pescadores diante do Recife Mesoamericano. De dia chegam os cruzeiros; à noite o calçadão é tranquilo.", "Fique a noite. Quando os navios partem, a vila volta a ser sua."],
      banco_chinchorro: ["Banco Chinchorro", "Reserva da Biosfera e maior atol de coral do México, com naufrágios entre os recifes. Saídas de Mahahual.", "As saídas dependem do tempo; reserve com um dia de folga."],
      chacchoben: ["Zona Arqueológica de Chacchobén", "Templos maias escondidos na selva, com árvores centenárias e bugios por perto.", "Chegue na abertura para tê-lo quase só para você."],
      kohunlich: ["Kohunlich", "Famoso pelo Templo das Máscaras, rostos de estuque de vários metros voltados para o leste.", "Combine com Dzibanché no mesmo dia."],
      dzibanche: ["Dzibanché", "Uma das grandes capitais maias do sul de Quintana Roo, no meio da selva e com pouquíssimos visitantes.", "Leve repelente; a selva é densa."],
      museo_cultura_maya: ["Museu da Cultura Maia", "Em Chetumal. A visão de mundo maia em três níveis, do inframundo ao céu.", "Bom refúgio para as horas mais quentes."],
      boulevard_bahia: ["Calçadão da Baía de Chetumal", "A orla da capital, diante da baía onde vive o peixe-boi. À noite enche de famílias, barracas e brisa.", "Prove salbutes nas barracas perto da orla."],
    },
  },

  // -------------------------------------------------------------------- comida
  comida: {
    cancun: ["cochinita", "sopa_lima", "tikin_xic", "poc_chuc", "esquites"],
    riviera_maya: ["tikin_xic", "cochinita", "papadzules", "poc_chuc", "esquites"],
    gran_costa_maya: ["salbutes", "panuchos", "relleno_negro", "pan_cazon", "tikin_xic"],
  },
  platillos: {
    cochinita: { foto: "comida_cochinita", es: ["Cochinita pibil", "Cerdo marinado en achiote y naranja agria, cocido lento. Se come en tacos o tortas, de preferencia en la mañana."], en: ["Cochinita pibil", "Pork marinated in achiote and sour orange, slow-cooked. Eaten in tacos or tortas, ideally in the morning."], fr: ["Cochinita pibil", "Porc mariné au rocou et à l'orange amère, cuit lentement. En tacos ou tortas, de préférence le matin."], pt: ["Cochinita pibil", "Porco marinado em urucum e laranja-azeda, cozido lentamente. Comido em tacos ou tortas, de preferência de manhã."] },
    sopa_lima: { foto: "comida_sopa_lima", es: ["Sopa de lima", "Caldo de pollo con lima yucateca y tiras de tortilla frita. Ligera y perfecta para el calor."], en: ["Lime soup", "Chicken broth with Yucatecan lime and fried tortilla strips. Light and perfect for the heat."], fr: ["Soupe au citron vert", "Bouillon de poulet au citron yucatèque et lamelles de tortilla frite. Léger, idéal par la chaleur."], pt: ["Sopa de lima", "Caldo de frango com lima iucateca e tiras de tortilha frita. Leve e perfeita para o calor."] },
    tikin_xic: { foto: "comida_tikin_xic", es: ["Pescado tikin xic", "Pescado abierto, untado de achiote y asado a las brasas en hoja de plátano. El clásico frente al mar."], en: ["Tikin xic fish", "Butterflied fish rubbed with achiote and grilled in banana leaf. The seaside classic."], fr: ["Poisson tikin xic", "Poisson ouvert, badigeonné de rocou et grillé dans une feuille de bananier. Le classique en bord de mer."], pt: ["Peixe tikin xic", "Peixe aberto, com urucum, assado na brasa em folha de bananeira. O clássico à beira-mar."] },
    poc_chuc: { foto: "comida_poc_chuc", es: ["Poc chuc", "Cerdo asado marinado en naranja agria, con cebolla asada, frijol y aguacate."], en: ["Poc chuc", "Grilled pork marinated in sour orange, with grilled onion, beans and avocado."], fr: ["Poc chuc", "Porc grillé mariné à l'orange amère, avec oignon grillé, haricots et avocat."], pt: ["Poc chuc", "Porco grelhado marinado em laranja-azeda, com cebola grelhada, feijão e abacate."] },
    esquites: { foto: "comida_esquites", es: ["Esquites", "Granos de elote con mayonesa, queso, limón y chile. El antojo de la noche en el parque."], en: ["Esquites", "Corn kernels with mayo, cheese, lime and chili. The night-time snack at the plaza."], fr: ["Esquites", "Grains de maïs avec mayonnaise, fromage, citron vert et piment. Le snack du soir sur la place."], pt: ["Esquites", "Grãos de milho com maionese, queijo, limão e pimenta. O petisco da noite na praça."] },
    papadzules: { foto: "comida_papadzules", es: ["Papadzules", "Tortillas rellenas de huevo, bañadas en salsa de pepita de calabaza y jitomate. Receta maya."], en: ["Papadzules", "Tortillas filled with egg, covered in pumpkin-seed and tomato sauce. A Maya recipe."], fr: ["Papadzules", "Tortillas farcies à l'œuf, nappées de sauce aux graines de courge et tomate. Recette maya."], pt: ["Papadzules", "Tortilhas recheadas com ovo, cobertas com molho de semente de abóbora e tomate. Receita maia."] },
    salbutes: { foto: "comida_salbutes", es: ["Salbutes", "Tortilla inflada y frita con pavo, lechuga, tomate y cebolla morada. La cena típica de Chetumal."], en: ["Salbutes", "Puffed fried tortilla topped with turkey, lettuce, tomato and pickled red onion. Chetumal's classic dinner."], fr: ["Salbutes", "Tortilla gonflée et frite garnie de dinde, laitue, tomate et oignon rouge. Le dîner typique de Chetumal."], pt: ["Salbutes", "Tortilha estufada e frita com peru, alface, tomate e cebola roxa. O jantar típico de Chetumal."] },
    panuchos: { foto: "comida_panuchos", es: ["Panuchos", "Parecidos al salbut, pero rellenos de frijol. Se piden por pieza y se comparten."], en: ["Panuchos", "Like salbutes, but stuffed with black beans. Order by the piece and share."], fr: ["Panuchos", "Comme les salbutes, mais farcis de haricots noirs. Se commandent à l'unité et se partagent."], pt: ["Panuchos", "Parecidos com salbutes, mas recheados de feijão. Pedidos por unidade para dividir."] },
    relleno_negro: { foto: "comida_relleno_negro", es: ["Relleno negro", "Guiso de pavo en recado de chiles quemados, con 'but' de carne y huevo cocido."], en: ["Relleno negro", "Turkey stew in a burnt-chili paste, with a meat-and-egg filling."], fr: ["Relleno negro", "Ragoût de dinde à la pâte de piments brûlés, avec farce de viande et œuf."], pt: ["Relleno negro", "Ensopado de peru em pasta de pimentas queimadas, com recheio de carne e ovo."] },
    pan_cazon: { foto: "comida_pan_cazon", es: ["Pan de cazón", "Capas de tortilla con cazón guisado, frijol y salsa de jitomate. De la costa sur."], en: ["Pan de cazón", "Layered tortillas with stewed dogfish, beans and tomato sauce. From the southern coast."], fr: ["Pan de cazón", "Tortillas superposées avec requin émietté, haricots et sauce tomate. De la côte sud."], pt: ["Pan de cazón", "Camadas de tortilha com cação ensopado, feijão e molho de tomate. Da costa sul."] },
  },
  consejos_comida: {
    es: ["La cochinita se acaba temprano: búscala en el desayuno.", "Pide la salsa de habanero aparte; pica de verdad.", "En los mercados y loncherías se come la cocina más local.", "Toma agua embotellada o purificada, no de la llave.", "La propina es voluntaria: Profeco indica que no pueden cobrarla ni incluirla en la cuenta sin tu permiso. Si el servicio te gustó, se acostumbra dejar 10 a 15 %."],
    en: ["Cochinita sells out early: have it for breakfast.", "Ask for the habanero salsa on the side; it's truly hot.", "Markets and small diners serve the most local food.", "Drink bottled or purified water, not tap water.", "Tipping is voluntary: Mexico's consumer agency (Profeco) says it can't be charged or added to the bill without your consent. If you liked the service, 10–15% is customary."],
    fr: ["La cochinita part vite : prends-la au petit-déjeuner.", "Demande la sauce habanero à part ; elle pique vraiment.", "Les marchés et petites cantines servent la cuisine la plus locale.", "Bois de l'eau en bouteille ou purifiée, pas celle du robinet.", "Le pourboire est volontaire : selon la Profeco, il ne peut pas être imposé ni ajouté à l'addition sans ton accord. Si le service t'a plu, 10 à 15 % est l'usage."],
    pt: ["A cochinita acaba cedo: procure no café da manhã.", "Peça o molho de habanero à parte; é bem picante.", "Nos mercados e lanchonetes se come a comida mais local.", "Beba água engarrafada ou purificada, não da torneira.", "A gorjeta é voluntária: segundo a Profeco, não pode ser cobrada nem incluída na conta sem sua autorização. Se gostou do serviço, costuma-se deixar 10 a 15%."],
  },

  // ------------------------------------------------------------------- postales
  postales: [
    { foto: "postal_cancun", es: "Cancún", en: "Cancún", fr: "Cancún", pt: "Cancún" },
    { foto: "bacalar_manana", es: "Amanecer en Bacalar", en: "Sunrise in Bacalar", fr: "Lever du soleil à Bacalar", pt: "Amanhecer em Bacalar" },
    { foto: "postal_playa", es: "Playa del Carmen", en: "Playa del Carmen", fr: "Playa del Carmen", pt: "Playa del Carmen" },
    { foto: "postal_tulum", es: "Playa Paraíso, Tulum", en: "Paraíso Beach, Tulum", fr: "Plage Paraíso, Tulum", pt: "Praia Paraíso, Tulum" },
    { foto: "postal_cenote", es: "Cenote en la Riviera Maya", en: "Cenote on the Riviera Maya", fr: "Cénote sur la Riviera Maya", pt: "Cenote na Riviera Maya" },
    { foto: "estromatolitos", es: "Estromatolitos de Bacalar", en: "Bacalar stromatolites", fr: "Stromatolithes de Bacalar", pt: "Estromatólitos de Bacalar" },
    { foto: "postal_xcacel", es: "Playa Xcacel", en: "Xcacel Beach", fr: "Plage Xcacel", pt: "Praia Xcacel" },
    { foto: "postal_bacalar", es: "Laguna de Bacalar", en: "Bacalar Lagoon", fr: "Lagune de Bacalar", pt: "Lagoa de Bacalar" },
    { foto: "postal_mahahual", es: "Mahahual", en: "Mahahual", fr: "Mahahual", pt: "Mahahual" },
    { foto: "postal_chetumal", es: "Bahía de Chetumal", en: "Chetumal Bay", fr: "Baie de Chetumal", pt: "Baía de Chetumal" },
    { foto: "mahahual_barcas", es: "Lanchas en Mahahual", en: "Boats in Mahahual", fr: "Barques à Mahahual", pt: "Barcos em Mahahual" },
    { foto: "sian_kaan", es: "Sian Ka'an", en: "Sian Ka'an", fr: "Sian Ka'an", pt: "Sian Ka'an" },
  ],

  // -------------------------------------------------------------- cómo moverte
  moverse: {
    es: [
      ["Aeropuertos", "Cancún (CUN) recibe la mayoría de los vuelos. También hay aeropuertos en Tulum (TQO) y Chetumal (CTM)."],
      ["Tren Maya", "Conecta Cancún, Playa del Carmen, Tulum, Bacalar y Chetumal. Cómodo para cruzar el estado sin manejar."],
      ["Autobús", "Las líneas de autobús unen todas las ciudades y pueblos grandes con salidas frecuentes."],
      ["Auto", "Cancún–Tulum son unos 130 km; Tulum–Bacalar, unos 210 km; Bacalar–Chetumal, unos 40 km (distancias aproximadas)."],
      ["Lancha y velero", "En Bacalar la laguna se recorre en velero o lancha; en Mahahual salen lanchas a Banco Chinchorro."],
    ],
    en: [
      ["Airports", "Cancún (CUN) gets most flights. There are also airports in Tulum (TQO) and Chetumal (CTM)."],
      ["Tren Maya", "Links Cancún, Playa del Carmen, Tulum, Bacalar and Chetumal. An easy way to cross the state without driving."],
      ["Bus", "Bus lines connect every city and large town with frequent departures."],
      ["Car", "Cancún–Tulum is about 130 km; Tulum–Bacalar about 210 km; Bacalar–Chetumal about 40 km (approximate)."],
      ["Boat & sailboat", "Bacalar lagoon is explored by sailboat or boat; in Mahahual, boats leave for Banco Chinchorro."],
    ],
    fr: [
      ["Aéroports", "Cancún (CUN) reçoit la plupart des vols. Il y a aussi des aéroports à Tulum (TQO) et Chetumal (CTM)."],
      ["Tren Maya", "Relie Cancún, Playa del Carmen, Tulum, Bacalar et Chetumal. Pratique pour traverser l'État sans conduire."],
      ["Bus", "Les lignes de bus relient toutes les villes avec des départs fréquents."],
      ["Voiture", "Cancún–Tulum : environ 130 km ; Tulum–Bacalar : environ 210 km ; Bacalar–Chetumal : environ 40 km (approximatif)."],
      ["Barque et voilier", "La lagune de Bacalar se visite en voilier ou en barque ; à Mahahual, des barques partent vers Banco Chinchorro."],
    ],
    pt: [
      ["Aeroportos", "Cancún (CUN) recebe a maioria dos voos. Também há aeroportos em Tulum (TQO) e Chetumal (CTM)."],
      ["Tren Maya", "Liga Cancún, Playa del Carmen, Tulum, Bacalar e Chetumal. Prático para cruzar o estado sem dirigir."],
      ["Ônibus", "As linhas de ônibus ligam todas as cidades com saídas frequentes."],
      ["Carro", "Cancún–Tulum são cerca de 130 km; Tulum–Bacalar, cerca de 210 km; Bacalar–Chetumal, cerca de 40 km (aproximado)."],
      ["Lancha e veleiro", "A lagoa de Bacalar se percorre de veleiro ou lancha; em Mahahual saem lanchas para o Banco Chinchorro."],
    ],
  },

  // ---------------------------------------------------------------------- FAQ
  // claves: palabras (sin acentos) que ayudan al asistente a encontrar la respuesta.
  faq: [
    { claves: ["mejor", "epoca", "temporada", "cuando", "best", "time", "when", "season", "meilleure", "quand", "melhor", "quando"],
      es: ["¿Cuál es la mejor época para ir?", "Depende del destino. En general, de septiembre a noviembre hay menos gente, y de diciembre a abril es temporada alta. Usa el calendario de olas para ver tu mes exacto."],
      en: ["When is the best time to go?", "It depends on the destination. In general, September to November is quieter and December to April is high season. Use the wave calendar to check your exact month."],
      fr: ["Quelle est la meilleure période ?", "Cela dépend de la destination. En général, septembre à novembre est plus calme et décembre à avril est la haute saison. Consulte le calendrier des vagues pour ton mois."],
      pt: ["Qual é a melhor época para ir?", "Depende do destino. Em geral, de setembro a novembro há menos gente e de dezembro a abril é alta temporada. Use o calendário de ondas para ver seu mês."] },
    { claves: ["sargazo", "alga", "algas", "sargassum", "seaweed", "sargasses", "sargaco"],
      es: ["¿Qué es el sargazo y cuándo llega?", "Es un alga que llega a las playas del Caribe, sobre todo de primavera a inicios del verano. La laguna de Bacalar y los cenotes no lo reciben, así que son el mejor plan esos meses."],
      en: ["What is sargassum and when does it arrive?", "It's a seaweed that washes onto Caribbean beaches, mostly from spring to early summer. Bacalar lagoon and the cenotes don't get it, so they're the best plan those months."],
      fr: ["Qu'est-ce que la sargasse et quand arrive-t-elle ?", "C'est une algue qui arrive sur les plages de la Caraïbe, surtout du printemps au début de l'été. La lagune de Bacalar et les cénotes n'en reçoivent pas."],
      pt: ["O que é o sargaço e quando chega?", "É uma alga que chega às praias do Caribe, sobretudo da primavera ao início do verão. A lagoa de Bacalar e os cenotes não recebem sargaço."] },
    { claves: ["huracan", "huracanes", "lluvia", "tormenta", "hurricane", "storm", "rain", "ouragan", "pluie", "furacao", "chuva"],
      es: ["¿Cuándo es la temporada de huracanes?", "La temporada oficial del Atlántico va del 1 de junio al 30 de noviembre, con más actividad de agosto a octubre. Si viajas en esos meses, contrata seguro y revisa los avisos oficiales."],
      en: ["When is hurricane season?", "The official Atlantic season runs June 1 to November 30, most active August to October. If you travel then, get insurance and check official alerts."],
      fr: ["Quand est la saison des ouragans ?", "La saison officielle de l'Atlantique va du 1er juin au 30 novembre, plus active d'août à octobre. Prends une assurance et suis les alertes officielles."],
      pt: ["Quando é a temporada de furacões?", "A temporada oficial do Atlântico vai de 1º de junho a 30 de novembro, mais ativa de agosto a outubro. Faça seguro e acompanhe os alertas oficiais."] },
    { claves: ["mover", "llegar", "transporte", "tren", "autobus", "camion", "get", "around", "train", "bus", "transport", "deplacer", "locomover", "onibus"],
      es: ["¿Cómo me muevo entre Cancún, Tulum y Bacalar?", "Con el Tren Maya, en autobús o en auto. El tren y el autobús conectan Cancún, Playa del Carmen, Tulum, Bacalar y Chetumal."],
      en: ["How do I get between Cancún, Tulum and Bacalar?", "By Tren Maya, bus or car. Train and buses connect Cancún, Playa del Carmen, Tulum, Bacalar and Chetumal."],
      fr: ["Comment aller de Cancún à Tulum et Bacalar ?", "En Tren Maya, en bus ou en voiture. Le train et les bus relient Cancún, Playa del Carmen, Tulum, Bacalar et Chetumal."],
      pt: ["Como vou de Cancún a Tulum e Bacalar?", "De Tren Maya, ônibus ou carro. Trem e ônibus ligam Cancún, Playa del Carmen, Tulum, Bacalar e Chetumal."] },
    { claves: ["aeropuerto", "vuelo", "vuelos", "volar", "airport", "flight", "fly", "aeroport", "vol", "aeroporto", "voo"],
      es: ["¿A qué aeropuerto llego?", "Cancún (CUN) para el norte, Tulum (TQO) para la Riviera Maya y Chetumal (CTM) para Bacalar y Mahahual."],
      en: ["Which airport should I fly into?", "Cancún (CUN) for the north, Tulum (TQO) for the Riviera Maya and Chetumal (CTM) for Bacalar and Mahahual."],
      fr: ["Dans quel aéroport arriver ?", "Cancún (CUN) pour le nord, Tulum (TQO) pour la Riviera Maya et Chetumal (CTM) pour Bacalar et Mahahual."],
      pt: ["Para qual aeroporto devo voar?", "Cancún (CUN) para o norte, Tulum (TQO) para a Riviera Maya e Chetumal (CTM) para Bacalar e Mahahual."] },
    { claves: ["dinero", "pesos", "dolares", "tarjeta", "pagar", "efectivo", "money", "dollars", "card", "cash", "pay", "argent", "carte", "dinheiro", "cartao"],
      es: ["¿Pago con pesos, dólares o tarjeta?", "La moneda es el peso mexicano. En ciudades se acepta tarjeta; en pueblos pequeños, cenotes y puestos conviene llevar efectivo en pesos."],
      en: ["Do I pay in pesos, dollars or card?", "The currency is the Mexican peso. Cards work in cities; bring cash in pesos for small towns, cenotes and stalls."],
      fr: ["Je paie en pesos, dollars ou carte ?", "La monnaie est le peso mexicain. La carte fonctionne en ville ; prévois des pesos en espèces pour les villages, cénotes et stands."],
      pt: ["Pago em pesos, dólares ou cartão?", "A moeda é o peso mexicano. Cartão funciona nas cidades; leve pesos em dinheiro para vilas, cenotes e barracas."] },
    { claves: ["agua", "llave", "tomar", "beber", "water", "tap", "drink", "eau", "robinet", "boire", "torneira"],
      es: ["¿Se puede tomar el agua de la llave?", "No se recomienda. Toma agua embotellada o purificada; muchos hoteles tienen garrafones para rellenar."],
      en: ["Can I drink tap water?", "It's not recommended. Drink bottled or purified water; many hotels have refill jugs."],
      fr: ["Peut-on boire l'eau du robinet ?", "Ce n'est pas conseillé. Bois de l'eau en bouteille ou purifiée ; beaucoup d'hôtels ont des fontaines."],
      pt: ["Posso beber água da torneira?", "Não é recomendado. Beba água engarrafada ou purificada; muitos hotéis têm galões para reabastecer."] },
    { claves: ["bloqueador", "protector", "solar", "sunscreen", "sun", "creme", "cenote", "cenotes", "protetor"],
      es: ["¿Qué bloqueador uso?", "Biodegradable. En cenotes y en la laguna de Bacalar se pide cuidar el agua; en muchos cenotes debes ducharte antes de entrar."],
      en: ["Which sunscreen should I use?", "Biodegradable. Cenotes and Bacalar lagoon ask you to protect the water; many cenotes require a shower before you swim."],
      fr: ["Quelle crème solaire utiliser ?", "Biodégradable. Les cénotes et la lagune de Bacalar demandent de protéger l'eau ; beaucoup de cénotes exigent une douche avant."],
      pt: ["Que protetor solar usar?", "Biodegradável. Cenotes e a lagoa de Bacalar pedem cuidado com a água; muitos cenotes exigem banho antes de entrar."] },
    { claves: ["dias", "cuantos", "itinerario", "days", "how", "long", "itinerary", "jours", "combien", "quantos"],
      es: ["¿Cuántos días necesito?", "Una sugerencia: 3 o 4 días en Cancún, 3 o 4 en la Riviera Maya y 3 en Bacalar y Mahahual. Así recorres el estado sin prisas."],
      en: ["How many days do I need?", "A suggestion: 3–4 days in Cancún, 3–4 on the Riviera Maya and 3 in Bacalar and Mahahual. That covers the state unhurried."],
      fr: ["Combien de jours faut-il ?", "Suggestion : 3 ou 4 jours à Cancún, 3 ou 4 sur la Riviera Maya et 3 à Bacalar et Mahahual."],
      pt: ["Quantos dias preciso?", "Sugestão: 3 ou 4 dias em Cancún, 3 ou 4 na Riviera Maya e 3 em Bacalar e Mahahual."] },
    { claves: ["sur", "bacalar", "mahahual", "chetumal", "vale", "pena", "south", "worth", "sud", "sul"],
      es: ["¿Vale la pena ir al sur?", "Sí. Bacalar, Mahahual y Chetumal tienen la laguna de los siete colores, arrecife, zonas mayas en la selva y mucho menos gente. Quédate al menos una noche."],
      en: ["Is the south worth it?", "Yes. Bacalar, Mahahual and Chetumal offer the seven-color lagoon, reef, jungle Maya ruins and far fewer people. Stay at least one night."],
      fr: ["Le sud vaut-il le détour ?", "Oui. Bacalar, Mahahual et Chetumal offrent la lagune aux sept couleurs, le récif, des ruines mayas et beaucoup moins de monde. Restes-y au moins une nuit."],
      pt: ["Vale a pena ir ao sul?", "Sim. Bacalar, Mahahual e Chetumal têm a lagoa das sete cores, recife, ruínas maias na selva e muito menos gente. Fique pelo menos uma noite."] },
    { claves: ["tortugas", "tortuga", "nadar", "akumal", "turtles", "turtle", "swim", "tortues", "tartarugas"],
      es: ["¿Se puede nadar con tortugas?", "Sí, en la bahía de Akumal, pero está regulado: entra con guía, sin tocarlas y respetando las zonas marcadas."],
      en: ["Can I swim with turtles?", "Yes, in Akumal Bay, but it's regulated: go with a guide, don't touch them and respect marked areas."],
      fr: ["Peut-on nager avec les tortues ?", "Oui, dans la baie d'Akumal, mais c'est réglementé : avec un guide, sans les toucher."],
      pt: ["Dá para nadar com tartarugas?", "Sim, na baía de Akumal, mas é regulamentado: com guia, sem tocá-las e respeitando as áreas marcadas."] },
    { claves: ["prediccion", "confiable", "datos", "pronostico", "prediction", "reliable", "data", "forecast", "fiable", "previsao"],
      es: ["¿Qué tan confiable es la predicción?", "Es una estimación hecha con datos oficiales de turismo de Quintana Roo. Funciona por mes: te dice cómo suele estar ese mes, no un día exacto."],
      en: ["How reliable is the prediction?", "It's an estimate built from official Quintana Roo tourism data. It works by month: it tells you what that month is usually like, not an exact day."],
      fr: ["La prévision est-elle fiable ?", "C'est une estimation à partir des données officielles du tourisme. Elle fonctionne par mois, pas pour un jour précis."],
      pt: ["A previsão é confiável?", "É uma estimativa feita com dados oficiais de turismo. Funciona por mês, não para um dia exato."] },
  ],

  // ---------------------------------------------------------------- asistente
  bot: {
    es: {
      saludo: "¡Hola! Soy Temporada. Pregúntame cómo estará un destino en una fecha, cuándo ir, qué hacer, qué comer, dónde dormir, propinas, clima o transporte.",
      sugerencias: ["¿Cómo estará Cancún en marzo?", "¿Cuándo ir a Bacalar?", "¿Qué comer en Chetumal?", "¿Hay sargazo en junio?"],
      no_entendi: "Esa no me la sé todavía y prefiero no inventar. Pregúntame por un destino y una fecha, cuándo ir, qué hacer, qué comer, dónde dormir, propinas, clima o transporte.",
      estado: "{d} el {f}: {n}. {x}",
      mejor: "Las fechas más tranquilas para {d} son {m}.",
      hacer: "En {d} te recomiendo: {l}.",
      comer: "En {d} prueba {p}. Algunos lugares: {r}.",
      sargazo_si: "En {m}, las playas del sur están en temporada alta de sargazo. La laguna de Bacalar y los cenotes siguen perfectos.",
      sargazo_medio: "En {m} puede haber algo de sargazo en las playas del sur.",
      sargazo_no: "En {m} es temporada baja de sargazo.",
      pide_destino: "¿A qué destino? Cancún, Riviera Maya o Gran Costa Maya (Bacalar, Mahahual, Chetumal).",
      y: " y ",
    },
    en: {
      saludo: "Hi! Ask me when to go, how busy a place will be on a date, what to do or what to eat in Quintana Roo.",
      sugerencias: ["How busy is Cancún in March?", "When to visit Bacalar?", "What to eat in Chetumal?", "Is there sargassum in June?"],
      no_entendi: "I don't have that answer yet. Try asking about a date, a destination, food or sargassum.",
      estado: "{d} on {f}: {n}. {x}",
      mejor: "The quietest dates for {d} are {m}.",
      hacer: "In {d} I recommend: {l}.",
      comer: "In {d} try {p}. Some places: {r}.",
      sargazo_si: "In {m}, southern beaches are in peak sargassum season. Bacalar lagoon and the cenotes stay perfect.",
      sargazo_medio: "In {m} there may be some sargassum on southern beaches.",
      sargazo_no: "{m} is low sargassum season.",
      pide_destino: "Which destination? Cancún, Riviera Maya or Gran Costa Maya (Bacalar, Mahahual, Chetumal).",
      y: " and ",
    },
    fr: {
      saludo: "Bonjour ! Demande-moi quand partir, l'affluence à une date, quoi faire ou quoi manger au Quintana Roo.",
      sugerencias: ["Cancún en mars ?", "Quand aller à Bacalar ?", "Que manger à Chetumal ?", "Des sargasses en juin ?"],
      no_entendi: "Je n'ai pas encore cette réponse. Demande-moi une date, une destination, la cuisine ou les sargasses.",
      estado: "{d} le {f} : {n}. {x}",
      mejor: "Les dates les plus calmes pour {d} : {m}.",
      hacer: "À {d}, je te conseille : {l}.",
      comer: "À {d}, goûte {p}. Quelques adresses : {r}.",
      sargazo_si: "En {m}, les plages du sud sont en pleine saison des sargasses. La lagune de Bacalar et les cénotes restent parfaits.",
      sargazo_medio: "En {m}, il peut y avoir quelques sargasses sur les plages du sud.",
      sargazo_no: "{m} est une période de peu de sargasses.",
      pide_destino: "Quelle destination ? Cancún, Riviera Maya ou Gran Costa Maya (Bacalar, Mahahual, Chetumal).",
      y: " et ",
    },
    pt: {
      saludo: "Olá! Pergunte quando ir, como vai estar um destino numa data, o que fazer ou o que comer em Quintana Roo.",
      sugerencias: ["Como está Cancún em março?", "Quando ir a Bacalar?", "O que comer em Chetumal?", "Tem sargaço em junho?"],
      no_entendi: "Ainda não tenho essa resposta. Pergunte sobre uma data, um destino, comida ou sargaço.",
      estado: "{d} em {f}: {n}. {x}",
      mejor: "As datas mais tranquilas para {d} são {m}.",
      hacer: "Em {d} recomendo: {l}.",
      comer: "Em {d} prove {p}. Alguns lugares: {r}.",
      sargazo_si: "Em {m}, as praias do sul estão na alta temporada de sargaço. A lagoa de Bacalar e os cenotes continuam perfeitos.",
      sargazo_medio: "Em {m} pode haver algum sargaço nas praias do sul.",
      sargazo_no: "{m} é temporada baixa de sargaço.",
      pide_destino: "Qual destino? Cancún, Riviera Maya ou Gran Costa Maya (Bacalar, Mahahual, Chetumal).",
      y: " e ",
    },
  },
};
